#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const DIR = __dirname;
const ROOT = path.join(DIR, '..');
const db = JSON.parse(fs.readFileSync(path.join(DIR, 'card_database.json'), 'utf8'));
const nonLand = db.filter(c => c.type !== 'Land');
const authored = nonLand.filter(c => c.text && c.flavor);
const remaining = nonLand.filter(c => !c.text || !c.flavor);
const by = {};
remaining.forEach(c => { by[c.color] = (by[c.color] || 0) + 1; });

let sha = '';
let msg = '';
try {
  sha = execSync('git rev-parse --short HEAD', { cwd: ROOT, encoding: 'utf8' }).trim();
  msg = execSync('git log -1 --pretty=%s', { cwd: ROOT, encoding: 'utf8' }).trim();
} catch (e) {
  sha = 'unknown';
  msg = '';
}

const stamp = new Date().toISOString().slice(0, 10);
const out = [
  '# Current State (auto)',
  '',
  'Generated by `tcg-web-prototype/update-handoff.js`. Do not hand-edit.',
  '',
  '- **Date:** ' + stamp,
  '- **HEAD:** `' + sha + '` ' + msg,
  '- **Cards:** ' + db.length + ' total, ' + nonLand.length + ' non-land',
  '- **Authored text+flavor:** ' + authored.length + '/' + nonLand.length,
  '- **Remaining:** ' + remaining.length + (remaining.length ? ' ' + JSON.stringify(by) : ''),
  '- **Tests:** run `node recall_ominous_test.js` (do not hard-code a count here)',
  '',
  'Voice: `docs/CREATIVE_IDENTITY.md` (TENTATIVE). Wave 8: `docs/AUTHORING_BRIEF_WAVE8.md`.',
  'Unity: off-limits (separate agent).',
  ''
].join('\n');

const dest = path.join(ROOT, 'docs', 'CURRENT.md');
fs.writeFileSync(dest, out);
console.log('Wrote ' + dest);
