const fs = require('fs');
const path = require('path');
const cards = JSON.parse(fs.readFileSync(path.join(__dirname, 'cards.json'), 'utf8'));

const instantAbilities = {
  281:[{name:'Lava Dart',trigger:'on_cast',effect:'damage_any_target',value:1}],
  282:[{name:'Flame Burst',trigger:'on_cast',effect:'damage_random_enemy',value:4}],
  283:[{name:'Magma Spray',trigger:'on_cast',effect:'damage_random_enemy',value:2}],
  284:[{name:'Volcanic Hammer',trigger:'on_cast',effect:'damage_random_enemy',value:4}],
  285:[{name:'Ember Gale',trigger:'on_cast',effect:'damage_all_enemies',value:2}],
  286:[{name:'Inferno Trap',trigger:'on_cast',effect:'damage_random_enemy',value:3}],
  287:[{name:'Ash Cloud',trigger:'on_cast',effect:'damage_all_enemies',value:1}],
  288:[{name:'Magma Quake',trigger:'on_cast',effect:'damage_all_enemies',value:3}],
  289:[{name:'Firebrand',trigger:'on_cast',effect:'damage_two_targets',value:2}],
  290:[{name:'Cinder Storm',trigger:'on_cast',effect:'damage_all_enemies',value:3}],
  291:[{name:'Giant Growth',trigger:'on_cast',effect:'create_token',value:1,tokenPower:1,tokenToughness:1,tokenName:'Saproling'}],
  292:[{name:'Vine Snare',trigger:'on_cast',effect:'bounce_champion',value:0}],
  293:[{name:"Nature's Bounty",trigger:'on_cast',effect:'draw_cards',value:1},{name:"Forage",trigger:'on_cast',effect:'ramp_search_land',value:1}],
  294:[{name:'Bramble Bash',trigger:'on_cast',effect:'damage_random_enemy',value:3}],
  295:[{name:'Root Shield',trigger:'on_cast',effect:'create_token',value:2,tokenPower:1,tokenToughness:1,tokenName:'Saproling'}],
  296:[{name:'Wild Charge',trigger:'on_cast',effect:'damage_random_enemy',value:4}],
  297:[{name:'Overgrow',trigger:'on_cast',effect:'create_token',value:1,tokenPower:2,tokenToughness:2,tokenName:'Saproling'}],
  298:[{name:'Timber Salvo',trigger:'on_cast',effect:'damage_all_enemies',value:2}],
  299:[{name:'Feral Charge',trigger:'on_cast',effect:'create_token',value:1,tokenPower:3,tokenToughness:3,tokenName:'Beast'}],
  300:[{name:"Nature's Resolve",trigger:'on_cast',effect:'draw_cards',value:2},{name:"Bountiful Harvest",trigger:'on_cast',effect:'ramp_search_land',value:1}],
  301:[{name:'Fatal Push',trigger:'on_cast',effect:'destroy_weakest_enemy',value:1}],
  302:[{name:'Doom Blade',trigger:'on_cast',effect:'destroy_weakest_enemy',value:3}],
  303:[{name:'Dark Bargain',trigger:'on_cast',effect:'draw_cards',value:2}],
  304:[{name:'Soul Reap',trigger:'on_cast',effect:'destroy_weakest_enemy',value:3}],
  305:[{name:'Withering Gaze',trigger:'on_cast',effect:'damage_random_enemy',value:2}],
  306:[{name:'Grasp of Darkness',trigger:'on_cast',effect:'destroy_weakest_enemy',value:4}],
  307:[{name:'Drain Life',trigger:'on_cast',effect:'drain_life',value:3}],
  308:[{name:'Ghoul Call',trigger:'on_cast',effect:'create_token',value:1,tokenPower:2,tokenToughness:2,tokenName:'Zombie'}],
  309:[{name:'Pestilence',trigger:'on_cast',effect:'drain_all_opponents',value:3}],
  310:[{name:'Dead Weight',trigger:'on_cast',effect:'damage_random_enemy',value:2}],
  311:[{name:'Boomerang',trigger:'on_cast',effect:'bounce_champion',value:0}],
  312:[{name:'Into the Roil',trigger:'on_cast',effect:'bounce_champion',value:0}],
  313:[{name:'Counterspell',trigger:'on_cast',effect:'bounce_all_enemies',value:1}],
  314:[{name:'Aether Snag',trigger:'on_cast',effect:'bounce_champion',value:0},{name:"Abyssal Path",trigger:'on_cast',effect:'ramp_search_land',value:1}],
  315:[{name:'Flood Recede',trigger:'on_cast',effect:'bounce_champion',value:0}],
  316:[{name:"Distant Melody",trigger:'on_cast',effect:'draw_cards',value:2},{name:"Mariner's Guide",trigger:'on_cast',effect:'ramp_search_land',value:1}],
  317:[{name:'Deep Sea Serpent',trigger:'on_cast',effect:'damage_random_enemy',value:3}],
  318:[{name:'Tidal Surge',trigger:'on_cast',effect:'bounce_two_enemies',value:0}],
  319:[{name:'Rift Bolt',trigger:'on_cast',effect:'damage_random_enemy',value:2}],
  320:[{name:'Vodalian Tactics',trigger:'on_cast',effect:'damage_two_targets',value:2}],
  321:[{name:'Mana Leak',trigger:'on_cast',effect:'damage_random_enemy',value:2}],
  322:[{name:'Repulse',trigger:'on_cast',effect:'bounce_champion',value:0}],
  323:[{name:'Disenchant',trigger:'on_cast',effect:'destroy_relic',value:0}],
  324:[{name:'Naturalize',trigger:'on_cast',effect:'destroy_relic',value:0}],
  325:[{name:'Lightning Bolt',trigger:'on_cast',effect:'damage_any_target',value:3}],
  326:[{name:'Fog',trigger:'on_cast',effect:'damage_random_enemy',value:1}],
  327:[{name:'Think Twice',trigger:'on_cast',effect:'draw_cards',value:2}],
  328:[{name:'Chaos Warp',trigger:'on_cast',effect:'destroy_weakest_enemy',value:4}],
  329:[{name:'Rush of Adrenaline',trigger:'on_cast',effect:'damage_random_enemy',value:3}],
  330:[{name:'Elixir of Immortality',trigger:'on_cast',effect:'drain_life',value:3}],
  338:[{name:'Mana Burn',trigger:'on_cast',effect:'damage_random_enemy',value:3}],
  339:[{name:'Echoing Rebuke',trigger:'on_cast',effect:'damage_two_targets',value:2}],
  340:[{name:'Corrosive Touch',trigger:'on_cast',effect:'destroy_relic',value:0}],
};

const spellAbilities = {
  35:[{name:'Quick Deal',trigger:'on_cast',effect:'draw_cards',value:1}],
  36:[{name:'Gold Rush',trigger:'on_cast',effect:'ramp_search_land',value:1}],
  37:[{name:'Cornered Market',trigger:'on_cast',effect:'damage_random_enemy',value:3}],
  38:[{name:'Payday Advance',trigger:'on_cast',effect:'draw_cards',value:1}],
  39:[{name:'Hostile Takeover',trigger:'on_cast',effect:'damage_all_enemies',value:2}],
  75:[{name:'Overgrowth',trigger:'on_cast',effect:'create_token',value:2,tokenPower:1,tokenToughness:1,tokenName:'Saproling'}],
  76:[{name:'Wild Rage',trigger:'on_cast',effect:'damage_random_enemy',value:4}],
  77:[{name:"Nature's Rebuke",trigger:'on_cast',effect:'destroy_weakest_enemy',value:3},{name:"Rampant Growth",trigger:'on_cast',effect:'ramp_search_land',value:1}],
  78:[{name:'Season of Growth',trigger:'on_cast',effect:'draw_cards',value:3}],
  79:[{name:'Feral Instinct',trigger:'on_cast',effect:'create_token',value:1,tokenPower:3,tokenToughness:3,tokenName:'Beast'}],
  80:[{name:'Mycelium Burst',trigger:'on_cast',effect:'damage_all_enemies',value:3}],
  118:[{name:'Withering Touch',trigger:'on_cast',effect:'damage_random_enemy',value:1}],
  119:[{name:'Soul Drain',trigger:'on_cast',effect:'drain_life',value:3}],
  120:[{name:'Plague Wind',trigger:'on_cast',effect:'destroy_weakest_enemy',value:5}],
  158:[{name:'Tidecall',trigger:'on_cast',effect:'bounce_two_enemies',value:0}],
  159:[{name:'Abyssal Surge',trigger:'on_cast',effect:'damage_all_enemies',value:2}],
  160:[{name:'Riptide Crush',trigger:'on_cast',effect:'bounce_all_enemies',value:2}],
  185:[{name:'Bolt',trigger:'on_cast',effect:'damage_any_target',value:2}],
  186:[{name:'Reinforce',trigger:'on_cast',effect:'create_token',value:1,tokenPower:2,tokenToughness:2,tokenName:'Golem'}],
  187:[{name:'Scrap Salvage',trigger:'on_cast',effect:'return_from_graveyard',value:1}],
  188:[{name:'Overclock',trigger:'on_cast',effect:'draw_cards',value:2}],
  189:[{name:'Disassemble',trigger:'on_cast',effect:'destroy_relic',value:0}],
  190:[{name:'Chain Lightning',trigger:'on_cast',effect:'damage_two_targets',value:2}],
  191:[{name:'Fortify',trigger:'on_cast',effect:'create_token',value:1,tokenPower:1,tokenToughness:1,tokenName:'Golem'}],
  192:[{name:'Mass Recall',trigger:'on_cast',effect:'bounce_all_enemies',value:2}],
  193:[{name:'Rust',trigger:'on_cast',effect:'damage_random_enemy',value:1}],
  194:[{name:'Forge Shield',trigger:'on_cast',effect:'create_token',value:2,tokenPower:1,tokenToughness:1,tokenName:'Golem'}],
  195:[{name:'Shrapnel Blast',trigger:'on_cast',effect:'damage_random_enemy',value:5}],
  196:[{name:'Neutralize',trigger:'on_cast',effect:'bounce_champion',value:0}],
  197:[{name:'Mind Spring',trigger:'on_cast',effect:'draw_cards',value:3}],
  198:[{name:'Scrapheap Purge',trigger:'on_cast',effect:'destroy_weakest_enemy',value:3}],
  199:[{name:'Pandemonium',trigger:'on_cast',effect:'damage_all_enemies',value:5}],
  201:[{name:'Eruption',trigger:'on_cast',effect:'damage_random_enemy',value:2}],
  202:[{name:'Lava Surge',trigger:'on_cast',effect:'damage_random_enemy',value:3}],
  203:[{name:'Magma Volley',trigger:'on_cast',effect:'damage_two_targets',value:2}],
  204:[{name:'Ashfall',trigger:'on_cast',effect:'damage_any_target',value:1}],
  205:[{name:'Caldera Blast',trigger:'on_cast',effect:'damage_all_enemies',value:3}],
  206:[{name:'Seismic Roar',trigger:'on_cast',effect:'damage_random_enemy',value:3}],
  207:[{name:'Verdant Bounty',trigger:'on_cast',effect:'create_token',value:2,tokenPower:1,tokenToughness:1,tokenName:'Saproling'}],
  208:[{name:'Rootbind',trigger:'on_cast',effect:'ramp_search_land',value:1}],
  209:[{name:'Timber Snap',trigger:'on_cast',effect:'damage_random_enemy',value:3}],
  210:[{name:'Wildfire Bloom',trigger:'on_cast',effect:'damage_all_enemies',value:2}],
  211:[{name:'Canopy Crash',trigger:'on_cast',effect:'damage_random_enemy',value:3},{name:"Wild Growth",trigger:'on_cast',effect:'ramp_search_land',value:1}],
  212:[{name:"Nature's Claim",trigger:'on_cast',effect:'destroy_relic',value:0}],
  213:[{name:'Dark Ritual',trigger:'on_cast',effect:'ramp_search_land',value:2}],
  214:[{name:'Grave Pact',trigger:'on_cast',effect:'destroy_all_enemies',value:0}],
  215:[{name:'Entomb',trigger:'on_cast',effect:'return_from_graveyard',value:1}],
  216:[{name:'Blight Decay',trigger:'on_cast',effect:'destroy_weakest_enemy',value:4}],
  217:[{name:'Necrotic Touch',trigger:'on_cast',effect:'destroy_weakest_enemy',value:3}],
  218:[{name:'Siphon Life',trigger:'on_cast',effect:'drain_life',value:2}],
  219:[{name:'Tidal Lock',trigger:'on_cast',effect:'tap_enemy_champion',value:1}],
  220:[{name:'Flood Surge',trigger:'on_cast',effect:'bounce_champion',value:0}],
  221:[{name:'Whirlpool',trigger:'on_cast',effect:'bounce_two_enemies',value:0}],
  222:[{name:'Brine Wave',trigger:'on_cast',effect:'draw_cards',value:1},{name:"Tidal Pool",trigger:'on_cast',effect:'ramp_search_land',value:1}],
  223:[{name:'Depth Charge',trigger:'on_cast',effect:'damage_all_enemies',value:4}],
  224:[{name:'Undertow Pull',trigger:'on_cast',effect:'bounce_champion',value:0},{name:"Depths Beckon",trigger:'on_cast',effect:'ramp_search_land',value:1}],
  225:[{name:'Runic Infusion',trigger:'on_cast',effect:'ramp_search_land',value:1}],
  226:[{name:'Arcane Catalyst',trigger:'on_cast',effect:'draw_cards',value:1}],
  227:[{name:'Mana Resonator',trigger:'on_cast',effect:'draw_cards',value:1}],
  228:[{name:'Pulse Drain',trigger:'on_cast',effect:'drain_life',value:4}],
  229:[{name:'World Shatter',trigger:'on_cast',effect:'destroy_all_enemies',value:0}],
  230:[{name:'Null Surge',trigger:'on_cast',effect:'damage_all_enemies',value:3}],
  331:[{name:'Mana Surge',trigger:'on_cast',effect:'ramp_search_land',value:1}],
  332:[{name:'Arcane Infusion',trigger:'on_cast',effect:'draw_cards',value:1}],
  333:[{name:'Soul Resonance',trigger:'on_cast',effect:'return_from_graveyard',value:1}],
};

const authored = new Set([21,28,29,35,61,64,70,74,104,152,153,341,343,345,349,355,363,364,365,373,485,1011,1060,1095,1059,1065,1036,1084,1113,1041,1047,1017,1071,149,145,353,38,233,291,361,117,1089,1097,215,193,185,1105,1112,1118,1015,1022,1087,1046,1063,1070,506,555,369,371,367,553,554,1013,1021,1085,1093,1032,342,346,347,348,344,354,370,1094,1096,273,278,279,280,334,335,336,337,1101,1109,1114,231,232,234,236,239,350,1012,262,263,268,270,1083,251,253,255,258,242,243,245,238,240,241,246,247,249,250,252,254,256,257,259,260,261,264,265,267,269,275,521,522,523,524,526,527,528,529,1037,1068,1019,356,358,357,494,499]);

const allNeed = [];
for (const c of cards) {
  if ((c.type === 'Instant' || c.type === 'Spell') && !authored.has(c.id)) {
    const ab = (c.type === 'Instant' ? instantAbilities[c.id] : spellAbilities[c.id]) || [];
    allNeed.push({id: c.id, name: c.name, type: c.type, color: c.color, abilities: ab});
  }
}

const factionOrder = {Crimson:0, Sunforged:1, Lantern:2, Gilded:3, Colorless:4, Zealot:5};
allNeed.sort((a,b) => (factionOrder[a.color]||99) - (factionOrder[b.color]||99));

const batch1 = allNeed.slice(0, 30);
console.log('BATCH 1 (30 cards):');
batch1.forEach(c => {
  console.log(c.id + '|' + c.type + '|' + c.name + '|' + c.color + '|' + JSON.stringify(c.abilities));
});